import { Inter } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import './globals.css';
import Navigation from '@/components/Navigation/Navigation';
import Link from 'next/link';
import getServerStatus from '../../lib/getServerStatus';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
// const getStatus = async() =>{
// }

export default async function RootLayout({ children }) {
  const serverStatus = await getServerStatus();
  console.log(serverStatus.status);
  return (
    <html lang='en'>
      <body className={inter.className}>
        {/* {children} */}
        {/* <!-- component --> */}
        <div className='flex h-full w-[1200px] m-auto'>
          <div className='w-80 flex fixed top-0 flex-col bg-white h-full'>
            <Link
              href={'/'}
              className='flex bg-primary text-white font-semibold items-center justify-center h-14 border-b'>
              Bangladesh Gold ID-card Builder
            </Link>
            <Navigation />
          </div>
          <Toaster position='bottom-center' />
          <div className='w-full mx-10 my-5 ml-[350px]'>{children}</div>
        </div>
      </body>
    </html>
  );
}
