import { Inter } from 'next/font/google';
import './globals.css';
import Navigation from '@/components/Navigation/Navigation';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        {/* {children} */}
        {/* <!-- component --> */}
        <div className='flex h-full '>
          <div className='w-72 flex  fixed top-0 left-0 flex-col bg-white h-full border-r '>
            <Link
              href={'/'}
              className='flex bg-primary text-white font-semibold items-center justify-center h-14 border-b'>
              Bangladesh Gold ID-card Builder
            </Link>
            <Navigation />
          </div>
          <div className='w-full m-10 ml-80'>{children}</div>
        </div>
      </body>
    </html>
  );
}
