import { Inter } from 'next/font/google';
import './globals.css';
import getServerStatus from '../../lib/getServerStatus';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const serverStatus = await getServerStatus();
  console.log(serverStatus.status);
  return (
    <html lang='en'>
      <body className={inter.className}>
        {children}
        {/* <!-- component --> */}
      </body>
    </html>
  );
}
